language: c++

dist: xenial

script:
  - git ls-files src/ | xargs clang-format -i && git diff --exit-code && make all && make bin/turing-test && bin/turing-test

  - git ls-files test/ | xargs clang-format -i
